# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e51f7793f28f251b31089c929a8c997e62f83e891a68627a45c4663900a3e1e374d2b4f1ba2c36c4266c439971c523dec85002a8a0ddc5d4acd48266e90fad

test:
  secret_key_base: e747b6ca49b9a8626622e3e53e5410b6104ee417fa2d3162f12acdf0e38676aa36b240dcabc08d0d8a7afcc3eb5494383461dd5104c1c6cce43a2e4b8c0d812a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
